version: '1'

services:
  db:
    image: kartoza/postgis:14-3.1
    volumes:
      - postgis-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=renting
      - POSTGRES_USER=admin
      - POSTGRES_PASS=admin
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    ports:
      - '5432:5432' # port  can be addressed to
    restart: on-failure
    healthcheck:
      test: 'exit 0'

  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: 'admin'
      RABBITMQ_DEFAULT_PASS: 'admin'
    ports:
      - 5673:5672
      - 15672:15672
#  app:
#    build: .
#    ports:
#      - "3000:3000"

volumes:
  postgis-data:
